[book]
authors = ["Denys Vitali"]
language = "en"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-css = ["custom.css"]
additional-js = ["custom.js"]
